# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 'WeeWX 5.0'
site_url: 'https://www.weewx.com'
site_author: "Tom Keffer <tkeffer@gmail.com>"
# do not display github info since it is always obscured anyway
#repo_url: https://github.com/weewx/weewx
#repo_name: WeeWX GitHub Repository
# Shut off the "edit on GitHub" feature:
edit_uri: ''
copyright: Copyright © 2009-2023 Thomas Keffer, Matthew Wall, and Gary Roderick, all rights reserved
theme:
  name: 'material'
  logo: 'images/logo-weewx.png'
  favicon: 'images/favicon.png'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest

  font:
    text: 'Noto Sans'
    code: 'Inconsolata Mono'

  palette:
    - scheme: default
      primary: teal
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - css/weewx_ui.css

docs_dir: 'docs_src'
site_dir: 'build/docs'

nav:
  - "Quick start":
    - Debian: ./quickstarts/debian.md
    - RedHat: ./quickstarts/redhat.md
    - SuSE: ./quickstarts/suse.md
    - pip: ./quickstarts/pip.md
    - git: ./quickstarts/git.md

  - "User's guide":
    - "System requirements": ./usersguide/system-requirements.md
    - "Installing WeeWX": ./usersguide/installing-weewx.md
    - "Where to find things" : ./usersguide/where.md
    - "Running WeeWX": ./usersguide/running-weewx.md
    - "Web server integration": ./usersguide/webserver-integration.md
    - "Backup & restore": ./usersguide/backing-up-weewx.md
    - "MySQL/MariaDB": ./usersguide/mysql-mariadb-config.md
    - "Troubleshooting":
      - "Overview": ./usersguide/troubleshooting/index.md
      - "Hardware Problems": ./usersguide/troubleshooting/hardware.md
      - "Software Problems": ./usersguide/troubleshooting/software.md
      - "Meteorological Problems": ./usersguide/troubleshooting/meteo.md
    - "Configuration options":
      - "Overview": ./usersguide/weewx-config-file/index.md
      - "General options": ./usersguide//weewx-config-file/general.md
      - "[Station]": ./usersguide/weewx-config-file/stations-config.md
      - "[StdRESTful]": ./usersguide/weewx-config-file/stdrestful-config.md
      - "[StdReport]": ./usersguide/weewx-config-file/stdreport-config.md
      - "[StdConvert]": ./usersguide/weewx-config-file/stdconvert-config.md
      - "[StdCalibrate]": ./usersguide/weewx-config-file/stdcalibrate-config.md
      - "[StdQC]": ./usersguide/weewx-config-file/stdqc-config.md
      - "[StdWXCalculate]": ./usersguide/weewx-config-file/stdwxcalculate-config.md
      - "[StdArchive]": ./usersguide/weewx-config-file/stdarchive.md
      - "[StdTimeSynch]": ./usersguide/weewx-config-file/stdtimesynch.md
      - "[DataBindings]": ./usersguide/weewx-config-file/data-bindings.md
      - "[Databases]": ./usersguide/weewx-config-file/databases.md
      - "[DatabaseTypes]": ./usersguide/weewx-config-file/databasetypes.md
      - "[Engine]": ./usersguide/weewx-config-file/engine.md

  - Customization guide:
    - "Introduction": custom/index.md
    - "Customizing reports": custom/custom-reports.md
    - "Scheduling reports": custom/report-scheduling.md
    - "The Cheetah generator": custom/cheetah.md
    - "The Image generator": custom/image-generator.md
    - "Multiple data bindings": custom/multiple-bindings.md
    - "Localization": custom/localization.md
    - "Customizing the service engine": custom/service-engine.md
    - "Customizing the database": custom/database.md
    - "Customizing units": custom/units.md
    - "Derived types": custom/derived.md
    - "Custom drivers": custom/drivers.md
    - "Extensions": custom/extensions.md
    - "Report options": custom/report-options.md
    - "Appendix": custom/appendix.md

  - Utilities:
    - weewxd: utilities/weewxd.md
    - weectl:
      - weectl station: utilities/weectl-station.md
      - weectl extension: utilities/weectl-extension.md
      - weectl database: utilities/weectl-database.md
    - wee_database: utilities/wee_database.md
    - wee_debug: utilities/wee_debug.md
    - wee_device: utilities/wee_device.md
    - wee_import: utilities/wee_import.md
    - wee_reports: utilities/wee_reports.md

  - "Hardware guide":
    - Drivers: hardware/drivers.md
    - AcuRite: hardware/acurite.md
    - CC3000: hardware/cc3000.md
    - FineOffset: hardware/fousb.md
    - TE923: hardware/te923.md
    - Ultimeter: hardware/ultimeter.md
    - Vantage: hardware/vantage.md
    - WMR100: hardware/wmr100.md
    - WMR300: hardware/wmr300.md
    - WMR9x8: hardware/wmr9x8.md
    - WS1: hardware/ws1.md
    - WS23xx: hardware/ws23xx.md
    - WS28xx: hardware/ws28xx.md

  - "Upgrade guide": upgrade.md
  - "Notes for developers": devnotes.md
  - "Change log": changes.md

plugins:
  - search

markdown_extensions:

  # Code highlighting in ``` ``` blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight
  - pymdownx.inlinehilite

  - pymdownx.superfences

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
  - pymdownx.details

  # linkifies URL and email links without having to wrap them in Markdown syntax. Also, allows shortens repository issue, pull request, and commit links.
  - pymdownx.magiclink

  # Highlight words with ==mark me==
  - pymdownx.mark

  # Adds support for strike through ~~strike me~~ and subscript text~a\ subscript~
  - pymdownx.tilde

  # Tabbed provides a syntax to easily add tabbed Markdown content.
  # https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets:
      # auto_append abbreviations.md to every file
      # https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary
      auto_append:
        - docs/abbreviations.md

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Adds the ability to define abbreviations (https://squidfunk.github.io/mkdocs-material/reference/tooltips/)
  - abbr

  # block-styled side content
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition

  - attr_list

  # Adds syntax for defining footnotes in Markdown documents (https://squidfunk.github.io/mkdocs-material/reference/footnotes/)
  - footnotes

  - md_in_html

  - tables

  # Table of Contents`
  # https://python-markdown.github.io/extensions/toc/
  - toc:
      permalink: true
