site_name: 'weewx documentation'
site_url: 'https://www.weewx.com'
repo_url: https://github.com/weewx/weewx
repo_name: WeeWX GitHub Repository
copyright: Copyright © Tom Keffer and Matthew Wall, all rights reserved
favicon: 'images/favicon.png'
theme:
  logo: 'images/logo-weewx.png'
  name: 'material'
  icon:
    logo: material/library
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  font:
    text: 'Noto Sans'
    code: 'Inconsolata Mono'

  palette:
    - scheme: default
      primary: teal
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - css/weewx_ui.css

site_dir: 'bin/wee_resources/docs'

nav:
  - Quickstarts:
      - quickstart-overview.md
      - Debian: debian.md
      - RedHat: redhat.md
      - SUSE: suse.md
      - pip: pip.md
      - "Migrating to V5": v5-upgrade.md

  - "User's guide":
      - "About WeeWX": ./userguide/about-weewx.md
      - "System Requirements": ./userguide/system-requirements.md
      - "Installing WeeWX": ./userguide/installing-weewx.md
      - "Running WeeWX": ./userguide/running-weewx.md
      - "WebServer Integration": ./userguide/webserver-integration.md
      - "Backup & Restore WeeWX": ./userguide/backing-up-weewx.md
      - "Configuring MySQL / MariaDB": ./userguide/mysql-mariadb-config.md
      - "weewx.conf config file": ./userguide/weewx.conf.md

  - 'Configuring WeeWX':
      - "weewx.conf Config File": ./weewx-config-file/overview.md
      - "General Options": ./weewx-config-file/general.md
      - "[Station]": ./weewx-config-file/stations-config.md
      - "[StdRESTful]": ./weewx-config-file/stdrestful-config.md
      - "[StdReport]": ./weewx-config-file/stdreport-config.md
      - "[StdConvert]": ./weewx-config-file/stdconvert-config.md
      - "[StdCalibrate]": ./weewx-config-file/stdcalibrate-config.md
      - "[StdQC]": ./weewx-config-file/stdqc-config.md
      - "[StdWXCalculate]": ./weewx-config-file/stdwxcalculate-config.md
      - "[StdArchive]": ./weewx-config-file/stdarchive.md
      - "[StdTimeSynch": ./weewx-config-file/stdtimesynch.md
      - "[DataBindings]": ./weewx-config-file/data-bindings.md
      - "[Databases]": ./weewx-config-file/databases.md
      - "[Engine]": ./weewx-config-file/engine.md

  - Customization guide:
    - "Introduction": custom/intro.md
    - "Customizing reports": custom/custom_reports.md
    - "The cheetah generator": custom/cheetah.md
    - "The image generator": custom/image_generator.md
    - "Multiple data bindings": custom/multiple_bindings.md
    - "Localization": custom/localization.md
    - "Customizing the service engine": custom/service_engine.md
    - "Customizing the database": custom/database.md
    - "Customizing units": custom/units.md
    - "Derived types": custom/derived.md
    - "Custom drivers": custom/drivers.md
    - "Extensions": custom/extensions.md
    - "Reference: options": custom/options_ref.md
    - "Appendix": custom/appendix.md

  - Other guides:
      - troubleshooting-guide.md
      - guides-overview.md
      - "Hardware guide": hardware.htm
      - "Utilities guide": utilities.htm
      - "Upgrade guide": upgrading.htm
      - "Change log": changes.md
      - "Notes for developers": devnotes.md
      - "Hardware comparison": hardware.htm
  - Support:
      - support.md

plugins:
  - search

markdown_extensions:

  # Code highlighting in ``` ``` blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
  - pymdownx.inlinehilite

  - pymdownx.superfences

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
  - pymdownx.details

  # linkifies URL and email links without having to wrap them in Markdown syntax. Also, allows shortens repository issue, pull request, and commit links.
  - pymdownx.magiclink

  # Task lists (https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/)
  - pymdownx.tasklist:
      custom_checkbox: true

  # Highlight words with ==mark me==
  - pymdownx.mark

  # Adds support for strike through ~~strike me~~ and subscript text~a\ subscript~
  - pymdownx.tilde

  # Tabbed provides a syntax to easily add tabbed Markdown content.
  # https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets:
      # auto_append abbreviations.md to every file
      # https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary
      auto_append:
        - docs/abbreviations.md

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Adds the ability to define abbreviations (https://squidfunk.github.io/mkdocs-material/reference/tooltips/)
  - abbr

  # block-styled side content
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition

  - attr_list

  # Adds syntax for defining footnotes in Markdown documents (https://squidfunk.github.io/mkdocs-material/reference/footnotes/)
  - footnotes

  - md_in_html

  - tables

  # Table of Contents`
  # https://python-markdown.github.io/extensions/toc/
  - toc:
      permalink: true
